services:
  - type: web
    name: portfolio-thymeleaf
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: PORT
        value: 8080